export { default as Home } from './home/home'
export { default as ProductInput } from './product-input/product-input'
export { default as Blogs } from './blogs/blogs'
export { default as Blog } from './blog/blog'
export { default as MyBusiness } from './my-business/my-business'
export { default as Product } from './product/productInfo'
export { default as SignUp } from './sign-up/sign-up'
export { default as Categories } from './categories/categories'
export { default as Categori } from './categori/categori'

